services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    networks:
      - firefly_iii
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - '5024:8080' # 5024 es el puerto de la interfaz de usuario de Firefly III
    depends_on:
      - db

  parser:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5025:8080" # 5025 es el puerto de la interfaz de usuario para importar cartolas bancarias de Chile
    volumes:
      - ./backend/app:/app
    env_file:
      - ./.backend.env
    depends_on:
      - db
    restart: always
    networks:
      - firefly_iii
  
  db:
    image: mariadb:lts
    hostname: db
    container_name: firefly_iii_db
    networks:
      - firefly_iii
    restart: always
    env_file: .db.env
    volumes:
      - firefly_iii_db:/var/lib/mysql

  importer:
    image: fireflyiii/data-importer:latest
    hostname: importer
    restart: always
    container_name: firefly_iii_importer
    networks:
      - firefly_iii
    ports:
      - '5023:8080' # 5023 es el puerto de la interfaz de usuario de la importación default de Firefly III
    depends_on:
      - app
    volumes:
      - ./backend/app/processed:/app/processed
      - ./backend/app/configs:/app/configs
    env_file: .importer.env

  cron:
    #
    # Para hacer que esto funcione, establezca STATIC_CRON_TOKEN en su archivo .env o como una variable de entorno y reemplace REPLACEME a continuación
    # El STATIC_CRON_TOKEN debe tener *exactamente* 32 caracteres de longitud
    #
    image: alpine
    container_name: firefly_iii_cron
    restart: always
    # firefly.example.cl debe ser reemplazado por su dominio de Firefly III
    command: sh -c "echo \"0 3 * * * wget -qO- https://firefly.example.cl/api/v1/cron/STATIC_CRON_TOKEN\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - firefly_iii
volumes:
   firefly_iii_upload:
   firefly_iii_db:

networks:
  firefly_iii:
    driver: bridge